### ISSUE TITLE
Improved Shield Block ID - Not found

### ISSUE THREAD

**Issue by Zeaper001** [Quadzet/Quadzet.github.io#24]
https://quadzet.github.io/TankSim/

From config.js
![impSB](https://github.com/Quadzet/Quadzet.github.io/assets/10898571/8cccded2-0a58-4797-a532-5dd53210c222)

The element doesn't exist in index.html

Seen by following JS error:
**Uncaught TypeError: Cannot read properties of null (reading 'value')**

**Solution purpose:**
add the missing html
`<div class="hInput"><label>Improved Shield Block:</label><input class="talent-input" type="number" id="impSB" name="impSB" min="0" max="5" value="1">/5</div>`

**Comment by Quadzet** [comment]
Thank you!
I accidentally added the impSB lines in the vanilla tanksim instead of the SoD sim, unfortunately the vanilla sim doesn't support imp SB. I'll just remove the references to it.
